<?xml version="1.0" encoding="UTF-8"?>
<TestSuiteEntity>
   <description></description>
   <name>DataDrivenTests</name>
   <tag></tag>
   <isRerun>false</isRerun>
   <mailRecipient></mailRecipient>
   <numberOfRerun>0</numberOfRerun>
   <pageLoadTimeout>30</pageLoadTimeout>
   <pageLoadTimeoutDefault>true</pageLoadTimeoutDefault>
   <rerunFailedTestCasesOnly>false</rerunFailedTestCasesOnly>
   <rerunImmediately>false</rerunImmediately>
   <testSuiteGuid>e20ade0b-e90e-4c08-9dd8-9e7a5a1cff1b</testSuiteGuid>
   <testCaseLink>
      <guid>cc837e81-9cb1-4d57-a7b1-72f73bb70ca4</guid>
      <isReuseDriver>false</isReuseDriver>
      <isRun>true</isRun>
      <testCaseId>Test Cases/tcDataDriven</testCaseId>
      <testDataLink>
         <combinationType>ONE</combinationType>
         <id>d672c809-58aa-473e-962f-addba5c661c0</id>
         <iterationEntity>
            <iterationType>ALL</iterationType>
            <value></value>
         </iterationEntity>
         <testDataId>Data Files/data</testDataId>
      </testDataLink>
      <variableLink>
         <testDataLinkId>d672c809-58aa-473e-962f-addba5c661c0</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>url</value>
         <variableId>695acc10-a97d-4592-ab0c-13e321d2af41</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>d672c809-58aa-473e-962f-addba5c661c0</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>username</value>
         <variableId>a590a2e1-62c3-4ade-9a8a-fd9fab957c6f</variableId>
      </variableLink>
      <variableLink>
         <testDataLinkId>d672c809-58aa-473e-962f-addba5c661c0</testDataLinkId>
         <type>DATA_COLUMN</type>
         <value>password</value>
         <variableId>d85c7838-5073-4add-9008-fdd836c73540</variableId>
      </variableLink>
   </testCaseLink>
</TestSuiteEntity>
